# General settings
parallel-jobs = 1
# =======================================
[Google-News]
enabled = true
app-name = "google-news"
version = "auto"
build-mode = "apk"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-news/"
