# General settings
enable-magisk-update = false # Set this to false to disable module updates in Magisk app
parallel-jobs = 1
patches-version = "dev"
# ======================================================================
# Spotify
# ======================================================================

[Spotify]
version = "auto"
app-name = "Spotify"
# arch = "arm64-v8a"
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts/"

[Spotify-anddea]
enabled = true
version = "auto"
app-name = "Spotify-anddea"
patches-source = "anddea/revanced-patches"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts/"
