# General settings
enable-magisk-update = false # Set this to false to disable module updates in Magisk app
parallel-jobs = 1

# ======================================================================
# Spotify
# ======================================================================

[Spotify]
version = "auto"
arch = "arm64-v8a"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Spotify-anddea]
enabled = true
app-name = "Spotify-anddea"
patches-source = "anddea/revanced-patches"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dpi = "120-640dpi"
version = "auto"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
